version: '2'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 32191:8080
    links:
      - db

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 32192:3306
    environment:
      MYSQL_ROOT_PASSWORD: ga4wm19
    volumes:
      - ../data/MySQL/:/var/lib/mysql

  webserver:
     build: ./Webserver/
     restart: always
     ports:
       - 32193:5002

  websocket:
     build: ./Websocket/
     restart: always
     ports:
       - 32194:6789

  nginx:
     image: nginx
     volumes:
      - ./:/usr/share/nginx/html
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf
     ports:
      - 32195:80
